### ISSUE TITLE
Human gene linkouts non-functional

### ISSUE THREAD

**Issue by robnash** [alliance-genome/agr#224] opened 2017-03-01 18:03 UTC
Hi,

Checking a few human genes, such as CDK1, HOTAIR and HOTTIP. When you go to the AGR gene page, the linkout to the respective database is listed as an HGNC link, but actually goes non-productively to RGD, where a numeric RGD ID is requested. 

Eg. http://staging.alliancegenome.org/gene/HGNC:37461 

and then click on Primary Source HGNC:37461, takes you here:

http://rgd.mcw.edu/rgdweb/report/gene/main.html?id=HGNC:37461

Should either GO here:

http://rgd.mcw.edu/rgdweb/report/gene/main.html?id=731889 

if the destination was intended to be RGD, or here:

http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:1722

if it was intended to go to HGNC.

Cheers,
Rob

**Comment by LucyHut** [comment] 2017-03-01 18:18
@robnash, see issue #207

**Comment by paaatrick** [comment] 2017-03-01 19:18
Yep, I'm going to close this out as a duplicate of #207.

**Closed by paaatrick** 2017-03-01 19:18 UTC
Labels: duplicate
