### ISSUE TITLE
Please stick to the editorconfig style guide for coding!

### ISSUE THREAD

**Issue by christabone** [alliance-genome/agr#169] opened 2017-02-23 18:52 UTC
As @kevinschaper mentioned in Slack, we're running into issue with a mixed tab/space codebase. Please [refer to the editorconfig](https://github.com/alliance-genome/agr/blob/development/.editorconfig) and code appropriately!

A whole crapload of tabs have creeped into the project. We should probably fix this after 0.3.0.

[Relevant Silicon Valley clip](https://www.youtube.com/watch?v=SsoOG6ZeyUI).

**Comment by bryon-czoch** [comment] 2017-02-23 19:11
Couldn't this be fixed with just a simple find & replace on the code base?

**Comment by oblodgett** [comment] 2017-02-23 19:27
I think this was primally caused by me. I have been in the java world with tabs, and non of my editors are setup for spaces. I think there might be a tool that would fix leading tabs to spaces.

**Comment by christabone** [comment] 2017-02-23 19:31
@bryon-czoch Yepper, it's easily fixable. Just putting the word out there.

**Closed** 2017-02-23 21:47 UTC
Labels: decision

**Comment by oblodgett** [comment] 2017-02-23 22:02
These need to be left open so that we can get the code in place to fix the issue, otherwise we just open a new issue.
